installCertmanager: false

# Settings for the Let's Encrypt ACME Issuer
certmanager-issuer:
   # The email address to register certificates requested from Let's Encrypt.
   # Required if using Let's Encrypt.
   email: email@local

gitlab-runner:
  install: false

nginx-ingress:
  enabled: false

global:
  edition: ce
  hosts:
    domain: local
    hostSuffix: staging
    https: false
    externalIP:
    gitlab:
      name: gitlab.local
      https: false
    registry:
      name: registry.local
      https: false
    minio:
      name: minio.local
      https: false
    smartcard:
      name: smartcard.local
    kas:
      name: kas.local
    pages:
      name: pages.local
      https: false
    ssh: gitlab.local
  ingress:
    enabled: false
    tls:
      enabled: false
